//english responses
#define WELCOME_MESSAGE_EN "Welcome to the shell help guide!\n"
#define BUILTIN_COMMANDS_EN "The following commands are built in:\n"
#define COMMAND_NOT_FOUND_EN "The command you gave is not part of CSEShell's builtin command\n"
#define COMMAND_USAGE_EN "Type: usage <command> to get help on a specific command.\n"
#define USAGE_CD_EN "Type: cd directory_name to change the current working directory of the shell\n"
#define USAGE_HELP_EN "Type: help for supported commands\n"
#define USAGE_EXIT_EN "Type: exit to terminate the shell gracefully\n"
#define USAGE_USAGE_EN "Type: usage cd/help/exit\n"
#define USAGE_ENV_EN "Type: env to list all registered env variables\n"
#define USAGE_SETENV_EN "Type: setenv ENV=VALUE to set a new env variable\n"
#define USAGE_UNSETENV_EN "Type: unsetenv ENV to remove this env from the list of env variables\n"


//the following are malay responses
#define WELCOME_MESSAGE_MS "Selamat datang ke panduan bantuan shell!\n"
#define BUILTIN_COMMANDS_MS "Perintah-perintah berikut adalah terbina dalam:\n"
#define COMMAND_NOT_FOUND_MS "Perintah yang anda berikan bukan sebahagian daripada perintah terbina dalam CSEShell\n"
#define COMMAND_USAGE_MS "Taip: usage <command> untuk mendapatkan bantuan mengenai perintah tertentu.\n"
#define USAGE_CD_MS "Taip: cd nama_direktori untuk menukar direktori kerja semasa shell\n"
#define USAGE_HELP_MS "Taip: help untuk senarai perintah yang disokong\n"
#define USAGE_EXIT_MS "Taip: exit untuk menamatkan shell dengan sempurna\n"
#define USAGE_USAGE_MS "Taip: usage cd/help/exit\n"
#define USAGE_ENV_MS "Taip: env untuk senarai semua pembolehubah persekitaran yang didaftarkan\n"
#define USAGE_SETENV_MS "Taip: setenv ENV=VALUE untuk menetapkan pembolehubah persekitaran baru\n"
#define USAGE_UNSETENV_MS "Taip: unsetenv ENV untuk mengeluarkan pembolehubah persekitaran dari senarai pembolehubah persekitaran\n"
